#!/bin/sh
# Builds the site into site/.
#
#   ./build.sh            # generate
#   ./build.sh --test     # run the generator's own test blocks
#
# Needs algc. If vendor/algol24 has not been built, this builds it -- which
# needs nothing but a C compiler, because the compiler's own output is checked
# in to bootstrap/.

set -e
cd "$(dirname "$0")"

# ⚠️ Both of these live under bootstrap/. The compiler repository moved them
# there, and the commit this submodule used to pin no longer exists on the
# remote -- CI failed on the checkout, not on the build. Keep this in step with
# the same two paths in .github/workflows/deploy.yml.
ALGC=vendor/algol24/bootstrap/algc

# ⚠️ Testing that algc EXISTS is not enough, and the difference has bitten.
# The submodule moves; the binary sitting in it does not. Bumping the pin to
# v0.1.2 left a v0.1.1 algc in place, this script found it and skipped the
# build, and the site was then generated by the previous compiler -- which
# fails only in CI, where the clone is fresh and there is no stale binary to
# find. Compare what the binary reports against what the pinned sources
# declare, and rebuild whenever they disagree.
want=$(sed -n "s/^const VERSION := '\(.*\)';/\1/p" vendor/algol24/compiler/Main.a24)
have=$([ -x "$ALGC" ] && "$ALGC" --version 2>/dev/null | awk '{ print $2 }')

if [ "$have" != "$want" ]; then
    if [ -z "$have" ]; then
        echo "algc not built; building the compiler first"
    else
        echo "algc is $have but the pinned sources are $want; rebuilding"
    fi
    ( cd vendor/algol24 && ./bootstrap/build.sh )
fi

if [ "${1-}" = "--test" ]; then
    # ⚠️ Two roots, and the second is temporary. --test is transitive over
    # 'uses', so naming Main runs everything Main can reach -- and it cannot
    # reach Markdown, because the reference page that unit exists for has not
    # been wired up yet and nothing imports it. Named on its own it would have
    # gone untested here and in CI, which is how sixteen passing tests turn
    # into no tests at all. Delete the second line the day Main uses Markdown.
    "$ALGC" --test gen/Main.a24 || exit 70
    exec "$ALGC" --test gen/Markdown.a24
fi

# ⚠️ The language cannot create a directory, so the output tree has to exist
# before the generator runs. This is the workaround that stops working the day
# the tree is decided by the content -- see WISHLIST-SITEGEN.md.
mkdir -p site

# The generator is COMPILED rather than interpreted, and then run.
#
# ⚠️ The gain is not where it looks. Compiling was worth 1.25x while the
# generator's time sat inside the C runtime -- a character index into a string
# holding any non-ASCII character walks from the start to find the byte offset,
# so ReadFile followed by Split was quadratic over the 352 KB specification and
# no back end could help. Reading straight into lines removed that, and only
# then did compiling start paying: 4.19s -> 0.44s interpreted, and 0.44s ->
# 0.01s compiled. Both changes, or neither is worth much.
#
# ⚠️ Emitted fresh every time. The directory is built with 'cc *.c', so a .c
# left behind by a module that has since been renamed would be compiled in
# alongside its replacement.
rm -rf build
mkdir -p build

"$ALGC" --compile --out=build gen/Main.a24
${CC:-cc} ${CFLAGS:--std=c11 -O2} -o build/generate build/*.c

./build/generate

cp -R static/. site/ 2>/dev/null || true
for f in favicon.ico favicon-16.png favicon-32.png apple-touch-icon.png \
         icon-192.png icon-512.png og-image.png; do
    [ -f "brand/dist/$f" ] && cp "brand/dist/$f" site/
done

# -I skips binaries: a PNG will contain the bytes '{{' sooner or later, and
# og-image.png duly did.
if grep -rnI '{{' site/ 2>/dev/null; then
    echo "FAIL  unrendered placeholder in the generated site"
    exit 70
fi

echo "site/ is ready"
