#!/bin/sh
# Builds the site into site/.
#
#   ./build.sh            # generate
#   ./build.sh --test     # run the generator's own test blocks
#
# Needs algc. If vendor/algol24 has not been built, this builds it -- which
# needs nothing but a C compiler, because the compiler's own output is checked
# in to bootstrap/.

set -e
cd "$(dirname "$0")"

# ⚠️ Both of these live under bootstrap/. The compiler repository moved them
# there, and the commit this submodule used to pin no longer exists on the
# remote -- CI failed on the checkout, not on the build. Keep this in step with
# the same two paths in .github/workflows/deploy.yml.
ALGC=vendor/algol24/bootstrap/algc

# ⚠️ Testing that algc EXISTS is not enough, and the difference has bitten.
# The submodule moves; the binary sitting in it does not. Bumping the pin to
# v0.1.2 left a v0.1.1 algc in place, this script found it and skipped the
# build, and the site was then generated by the previous compiler -- which
# fails only in CI, where the clone is fresh and there is no stale binary to
# find. Compare what the binary reports against what the pinned sources
# declare, and rebuild whenever they disagree.
want=$(sed -n "s/^const VERSION := '\(.*\)';/\1/p" vendor/algol24/compiler/Main.a24)
have=$([ -x "$ALGC" ] && "$ALGC" --version 2>/dev/null | awk '{ print $2 }')

if [ "$have" != "$want" ]; then
    if [ -z "$have" ]; then
        echo "algc not built; building the compiler first"
    else
        echo "algc is $have but the pinned sources are $want; rebuilding"
    fi
    ( cd vendor/algol24 && ./bootstrap/build.sh )
fi

if [ "${1-}" = "--test" ]; then
    exec "$ALGC" --test gen/Main.a24
fi

# ⚠️ The language cannot create a directory, so the output tree has to exist
# before the generator runs. This is the workaround that stops working the day
# the tree is decided by the content -- see WISHLIST-SITEGEN.md.
mkdir -p site

"$ALGC" gen/Main.a24

cp -R static/. site/ 2>/dev/null || true
for f in favicon.ico favicon-16.png favicon-32.png apple-touch-icon.png \
         icon-192.png icon-512.png og-image.png; do
    [ -f "brand/dist/$f" ] && cp "brand/dist/$f" site/
done

# -I skips binaries: a PNG will contain the bytes '{{' sooner or later, and
# og-image.png duly did.
if grep -rnI '{{' site/ 2>/dev/null; then
    echo "FAIL  unrendered placeholder in the generated site"
    exit 70
fi

echo "site/ is ready"
