#!/bin/sh
# Builds the site into site/.
#
#   ./build.sh            # generate
#   ./build.sh --test     # run the generator's own test blocks
#
# Needs algc. If vendor/algol24 has not been built, this builds it -- which
# needs nothing but a C compiler, because the compiler's own output is checked
# in to bootstrap/.

set -e
cd "$(dirname "$0")"

# ⚠️ Both of these live under bootstrap/. The compiler repository moved them
# there, and the commit this submodule used to pin no longer exists on the
# remote -- CI failed on the checkout, not on the build. Keep this in step with
# the same two paths in .github/workflows/deploy.yml.
ALGC=vendor/algol24/bootstrap/algc

# ⚠️ Testing that algc EXISTS is not enough, and the difference has bitten.
# The submodule moves; the binary sitting in it does not. Bumping the pin to
# v0.1.2 left a v0.1.1 algc in place, this script found it and skipped the
# build, and the site was then generated by the previous compiler -- which
# fails only in CI, where the clone is fresh and there is no stale binary to
# find. Compare what the binary reports against what the pinned sources
# declare, and rebuild whenever they disagree.
want=$(sed -n "s/^const VERSION := '\(.*\)';/\1/p" vendor/algol24/compiler/Main.a24)
have=$([ -x "$ALGC" ] && "$ALGC" --version 2>/dev/null | awk '{ print $2 }')

if [ "$have" != "$want" ]; then
    if [ -z "$have" ]; then
        echo "algc not built; building the compiler first"
    else
        echo "algc is $have but the pinned sources are $want; rebuilding"
    fi
    ( cd vendor/algol24 && ./bootstrap/build.sh )
fi

if [ "${1-}" = "--test" ]; then
    # One root again. --test is transitive over 'uses', and Main now imports
    # Markdown for the reference page, so naming Main reaches every unit.
    exec "$ALGC" --test gen/Main.a24
fi


# ⚠️ Every themed token must be declared in all THREE blocks, and nothing but a
# check enforces it. The rule has been written in CLAUDE.md from the start and
# was still broken by an edit that put four colours in the media block and none
# in [data-theme="dark"]: system dark looked right and the toggle served the
# light palette, which is the one combination nobody tests by accident.
#
# A token needs a dark value when its light value is a colour, which is what
# spares --measure and the two font stacks without an allowlist to maintain.
missing=$(awk '
    /^  :root \{/                    { block = "root";  next }
    /prefers-color-scheme: dark/      { block = "media"; next }
    /^  :root\[data-theme="dark"\]/   { block = "theme"; next }
    /^  \/\* ---- base/               { block = "";      next }
    block != "" && match($0, /--[a-z0-9-]+:/) {
        name = substr($0, RSTART, RLENGTH - 1)
        val  = substr($0, RSTART + RLENGTH)
        if (block == "root") { if (val ~ /#|rgba/) need[name] = 1 }
        else                 { have[block "|" name] = 1 }
    }
    END {
        for (n in need) {
            if (!(("media|" n) in have)) print "  " n " is not in the media block"
            if (!(("theme|" n) in have)) print "  " n " is not in [data-theme=dark]"
        }
    }' templates/site.css)

if [ -n "$missing" ]; then
    echo "FAIL  a themed token is declared in only some of the three blocks:"
    echo "$missing"
    exit 70
fi

# The site root, and only the root. v0.1.2 gave the language MkDir, so the
# generator makes site/reference itself -- the tree below here is decided by
# the content now, which is exactly what this mkdir used to stand in for.
mkdir -p site

# The generator is COMPILED rather than interpreted, and then run.
#
# ⚠️ The gain is not where it looks. Compiling was worth 1.25x while the
# generator's time sat inside the C runtime -- a character index into a string
# holding any non-ASCII character walks from the start to find the byte offset,
# so ReadFile followed by Split was quadratic over the 352 KB specification and
# no back end could help. Reading straight into lines removed that, and only
# then did compiling start paying: 4.19s -> 0.44s interpreted, and 0.44s ->
# 0.01s compiled. Both changes, or neither is worth much.
#
# ⚠️ Emitted fresh every time. The directory is built with 'cc *.c', so a .c
# left behind by a module that has since been renamed would be compiled in
# alongside its replacement.
rm -rf build
mkdir -p build

"$ALGC" --compile --out=build gen/Main.a24
${CC:-cc} ${CFLAGS:--std=c11 -O2} -o build/generate build/*.c

./build/generate

cp -R static/. site/ 2>/dev/null || true
for f in favicon.ico favicon-16.png favicon-32.png apple-touch-icon.png \
         icon-192.png icon-512.png og-image.png; do
    [ -f "brand/dist/$f" ] && cp "brand/dist/$f" site/
done

# -I skips binaries: a PNG will contain the bytes '{{' sooner or later, and
# og-image.png duly did.
if grep -rnI '{{' site/ 2>/dev/null; then
    echo "FAIL  unrendered placeholder in the generated site"
    exit 70
fi

echo "site/ is ready"
